### ISSUE TITLE
Grid state is not applied

### ISSUE THREAD

**Issue by wwonnink** [telerik-boneyard/extensions-for-asp-net-mvc-discontinued#1]
Hello,
i have applied your example in my code. I can see the pager settings are in the Routedata when I get back to page but they are not applied to the grid.
What am I doing wrong?
Kind regards,
Wilma

**Comment by KirilNN** [comment]
Hi @wwonnink,

I am afraid that this product has been discontinued long ago, and migrate to UI for MVC/ Kendo UI Professional. Therefore there is no ongoing development or custom support for it.
